### ISSUE TITLE
Component not showing up when used in .vue file

### ISSUE THREAD

**Issue by modasserbillah** [billyyyyy3320/vuepress-plugin-mailchimp#8]
Hi, I followed the docs and set the plugin up. It works as a charm when included in a `.md` file but doesn't show up when included in `.vue` files. I get the following error in the console:
```
 Unknown custom element: <SimpleNewsletter> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Thanks for the nice plugin. Appreciate your help!

**Comment by billyyyyy3320** [comment]
Thanks for the report. The import path of previous example was wrong. It has been updated. 

Please check the docs again. Now, you don't need to import or register the component manually.
